import dotenv from 'dotenv';
dotenv.config();

import axios from 'axios';
import { generateHostelAllotmentOrderPDF, HostelAllotmentData } from '../utils/allotmentGenerator';

const ZEPTO_API_URL = process.env.ZEPTO_API_URL || 'https://api.zeptomail.in/v1.1/email';
const ZEPTO_API_KEY = process.env.ZEPTO_API_KEY;
const ZEPTO_FROM_EMAIL = process.env.ZEPTO_FROM_EMAIL || '';
const ZEPTO_FROM_NAME = process.env.ZEPTO_FROM_NAME || '';

async function sendSampleHostelAllotment() {
    if (!ZEPTO_API_KEY) {
        console.error('ZEPTO_API_KEY is not set in environment');
        process.exit(1);
    }

    const sample: HostelAllotmentData = {
        applicationId: 'APP-2026-SAMPLE',
        studentName: 'Sri Krishna B H',
        fatherName: 'B Hari Prasad',
        motherName: 'B Lakshmi Devi',
        gender: 'Male',
        state: 'Andhra Pradesh',

        hostelName: 'Sri Sai Boys Hostel',
        hostelType: 'BOYS',
        roomNumber: 'B-204',
        bedNumber: 'B-204-2',
        floor: 2,
        sharing: 4,
        roomType: 'AC',
        paymentMode: 'YEARWISE',
        wardenName: 'Mr. Ramesh Kumar',

        accommodationPrice: 80000,
        messPrice: 45000,
        laundryPrice: 6000,
        registrationFee: 5000,
        effectiveTotal: 136000,

        reportingDate: '04.05.2026',
    };

    console.log('Generating sample hostel allotment PDF...');
    const pdfBuffer = await generateHostelAllotmentOrderPDF(sample);
    console.log(`Hostel Allotment PDF generated (${pdfBuffer.length} bytes)`);

    const toEmail = 'bhsrikrishna1994@gmail.com';
    const subject = 'Sample Hostel Allotment Order - VVITU ERP System';
    const htmlContent = `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
            <h2 style="color: #C0392B;">VVITU ERP - Sample Hostel Allotment Order</h2>
            <p>Attached is a sample <strong>Hostel Allotment Order</strong> PDF generated by the ERP for review.</p>
            <p><strong>Sample data summary:</strong></p>
            <ul>
                <li>Hostel: ${sample.hostelName} (${sample.hostelType})</li>
                <li>Room / Bed: ${sample.roomNumber} / ${sample.bedNumber} (Floor ${sample.floor})</li>
                <li>Sharing / Type: ${sample.sharing}-Sharing &middot; ${sample.roomType}</li>
                <li>Payment Mode: ${sample.paymentMode}</li>
                <li>Total Payable: INR ${sample.effectiveTotal.toLocaleString('en-IN')}</li>
            </ul>
            <p><strong>Sent at:</strong> ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p>
            <hr/>
            <p style="color: #999; font-size: 12px;">This is an automated sample from VVITU ERP System.</p>
        </div>
    `;

    try {
        const base64Pdf = pdfBuffer.toString('base64');

        const payload = {
            from: { address: ZEPTO_FROM_EMAIL, name: ZEPTO_FROM_NAME },
            to: [{ email_address: { address: toEmail } }],
            subject,
            htmlbody: htmlContent,
            attachments: [{
                name: 'Sample_Hostel_Allotment_Order.pdf',
                mime_type: 'application/pdf',
                content: base64Pdf
            }]
        };

        const response = await axios.post(ZEPTO_API_URL, payload, {
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'Authorization': ZEPTO_API_KEY
            },
            timeout: 30000
        });

        console.log('Email sent successfully!');
        console.log('Response:', JSON.stringify(response.data, null, 2));
    } catch (error: any) {
        console.error('Failed to send email:', error.response?.data || error.message);
    }
}

sendSampleHostelAllotment();
